### ISSUE TITLE
Vim complains about libsodium not available

### ISSUE THREAD

**Issue by Vinfall** [sileshn/SlackwareWSL2#1]
### Requirements

- [X] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Windows Build Number

Microsoft Windows [Version 10.0.25217.1000]

### Kernel Version

custom kernel (modded from 5.15.68.1-WSL2, available at https://github.com/Vinfall/Custom-WSL2-Kernel)

### Repro Steps

Open vim returns an error:

```sh
$ vim
vim: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory
```

### Expected Behavior

Vim should work out of the box.

I'm able to resolve the issue by running the following:
```sh
sudo slackpkg download libsodium
sudo slackpkg install-new libsodium
sudo ldconfig
```

I think add `libsodium` between `libgudev` and `libtool` in https://github.com/sileshn/SlackwareWSL2/blob/main/Makefile#L51 should prevent it.

### Actual Behavior

```sh
$ vim
vim: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory
```

**Comment by sileshn** [comment]
OK. Will make the necessary changes
