### ISSUE TITLE
Wrongfully will match any word in the row

### ISSUE THREAD

**Issue by makaiss0n** [sileshn/SlackwareWSL2#4]
### Requirements

- [ ] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Version

Microsoft Windows [Version 10.0.22000.2538]

### Repro Steps

Attempt to create a new user with user name matching with a word somewhere in the GECOS field will result in failure. Recommend adjusting the `grep` pattern to `^$username` to look for matches in the `username` field only.

### Expected Behavior

Allowing user to create new users with any user name, as long as it is not repeated actual user name.

### Actual Behavior

Can't create users with user name matching word in GECOS field.

**Comment by makaiss0n** [comment]
GitHub did not work as I expected; I am referencing [this](https://github.com/sileshn/SlackwareWSL2/blob/main/bash_profile#L132C22-L132C53).

**Comment by sileshn** [comment]
ok. will make the necessary changes in the next release
